version: 2.1
jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint 

  upload-docker:
    docker:
      - image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      # - run:
      #     name: install dependencies
      #     command: |
      #       apt update
      #       apt install -y python3-pip python3-venv
      #       python3 -V
      #       export DEBIAN_FRONTEND=noninteractive
      #       apt-get install -y tzdata
      #       ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
      #       dpkg-reconfigure --frontend noninteractive tzdata
      - run:
          name: install docker
          command: |        
            # echo "===== install docker ====="
            # apt install apt-transport-https ca-certificates curl software-properties-common -y
            # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            # add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            # apt-cache policy docker-ce
            # apt install docker-ce -y
            # systemctl status docker
            docker --version
      # - run:
      #     name: upload docker
      #     command: |
      #       . venv/bin/activate
      #       chmod +x upload_docker.sh
      #       ./upload_docker.sh

workflows:
  default:
    jobs:
      # - lint
      # - upload-docker:
      #     requires: [lint]
      - upload-docker